
#!/bin/bash -l



REMOTE_ROOT=$(readlink -f .)
echo 0 > $REMOTE_ROOT/2f94bde0fbc8351723837e39bdba90e6cb1bfb0a_flag_if_job_task_fail
test $? -ne 0 && exit 1




export DPDISPATCHER_NUMBER_NODE=1
export DPDISPATCHER_CPU_PER_NODE=1
export DPDISPATCHER_GPU_PER_NODE=0
export DPDISPATCHER_QUEUE_NAME=
export DPDISPATCHER_GROUP_SIZE=4



source $REMOTE_ROOT/2f94bde0fbc8351723837e39bdba90e6cb1bfb0a.sub.run

cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 2f94bde0fbc8351723837e39bdba90e6cb1bfb0a_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 2f94bde0fbc8351723837e39bdba90e6cb1bfb0a_job_tag_finished; else exit 1;fi



