#!/usr/bin/env python3
"""
lammps_tools.py — Generate LAMMPS input files for DeepMD/DPA MD simulations and collect results.

*** This tool ONLY supports pair_style deepmd. ***
*** Classical force fields (SW, Tersoff, EAM, ...) are NOT supported. ***
*** NEVER suggest classical potentials as alternatives. ***

By default the pretrained DPA3 model (from DEEPMD_MODEL_PATH) is frozen with the
Omat24 head (dp --pt freeze --head Omat24), same convention as ase-deepmd.

Commands
--------
  generate_input    Generate in.lammps + conf.lmp for a single structure.
  collect_results   Parse LAMMPS log files from completed jobs.
  show_model_path   Show the default DeePMD model path from env var.

Every command prints a JSON object to stdout and exits 0 on success, 1 on error.

Examples
--------
  # Simplest — model resolved from DEEPMD_MODEL_PATH, frozen with Omat24
  python lammps_tools.py generate_input --structures POSCAR

  # NVE at 600 K
  python lammps_tools.py generate_input \\
      --structures structures.extxyz \\
      --ensemble nve --temperature 600 --runtime_steps 500000

  # Specific model, no freezing
  python lammps_tools.py generate_input \\
      --structures POSCAR --model_path /path/to/model.pb --head none

  # All frames from multi-frame file
  python lammps_tools.py generate_input --structures traj.extxyz --frame -1

  # Collect results
  python lammps_tools.py collect_results \\
      --calc_dirs /tmp/lammps_jobs/job_001 /tmp/lammps_jobs/job_002
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import traceback
from datetime import datetime
from pathlib import Path
from typing import List, Optional

import yaml
from ase.data import atomic_masses, atomic_numbers
from ase.io import read

# ---------------------------------------------------------------------------
# Config / env helpers
# ---------------------------------------------------------------------------

_SCRIPT_DIR = Path(__file__).parent
_DEFAULT_CONFIG = _SCRIPT_DIR / "config.yaml"
_FROZEN_MODEL_FILENAME = "frozen_model.pth"


def _freeze_model(pretrained: Path, head: str, output: Path) -> Path:
    """Freeze a multi-task DeePMD model to a single-task one via ``dp freeze``."""
    cmd = ["dp", "--pt", "freeze", "-c", str(pretrained), "--head", head, "-o", str(output)]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"dp freeze failed (exit {result.returncode}):\n{result.stderr}"
        )
    if not output.exists():
        raise FileNotFoundError(f"Freeze command ran but output not found: {output}")
    return output


def _load_config(config_path: Path) -> dict:
    with open(config_path) as fh:
        return yaml.safe_load(fh)


def _load_env(config_path: Path) -> None:
    from dotenv import load_dotenv
    env_file = config_path.parent / ".env"
    if env_file.exists():
        load_dotenv(env_file, override=True)


def _default_model_path() -> Optional[Path]:
    """Return the default model path from DEEPMD_MODEL_PATH env var, or None."""
    val = os.environ.get("DEEPMD_MODEL_PATH")
    return Path(val) if val else None


def _job_id() -> str:
    return datetime.now().strftime("%Y%m%d%H%M%S_%f")


# ---------------------------------------------------------------------------
# LAMMPS data file generation
# ---------------------------------------------------------------------------

def _generate_lammps_data(atoms, data_path: Path) -> dict:
    """Convert an ASE Atoms object to a LAMMPS data file (real-space Cartesian coordinates).

    Atom types are assigned alphabetically by element symbol (1-based).
    Returns a dict with ``element_types`` (sorted list) and ``type_map``
    (element symbol -> 1-based type index).
    """
    symbols = sorted(set(atoms.get_chemical_symbols()))
    type_map = {s: i + 1 for i, s in enumerate(symbols)}

    cell = atoms.cell
    a, b, c = cell[0, 0], cell[1, 1], cell[2, 2]
    xy, xz, yz = cell[1, 0], cell[2, 0], cell[2, 1]

    positions = atoms.get_positions()
    chemical_symbols = atoms.get_chemical_symbols()

    with open(data_path, "w") as f:
        f.write("LAMMPS data file generated by lammps skill\n\n")
        f.write(f"{len(atoms)} atoms\n")
        f.write(f"{len(symbols)} atom types\n\n")
        f.write(f"0.0 {a:.10f} xlo xhi\n")
        f.write(f"0.0 {b:.10f} ylo yhi\n")
        f.write(f"0.0 {c:.10f} zlo zhi\n")
        if any(abs(v) > 1e-10 for v in [xy, xz, yz]):
            f.write(f"{xy:.10f} {xz:.10f} {yz:.10f} xy xz yz\n")

        f.write(f"\nMasses\n\n")
        for s in symbols:
            mass = atomic_masses[atomic_numbers[s]]
            f.write(f"{type_map[s]} {mass:.6f}  # {s}\n")

        f.write(f"\nAtoms  # atomic\n\n")
        for i, (pos, sym) in enumerate(zip(positions, chemical_symbols)):
            f.write(f"{i + 1} {type_map[sym]} {pos[0]:.10f} {pos[1]:.10f} {pos[2]:.10f}\n")

    return {"element_types": symbols, "type_map": type_map}


# ---------------------------------------------------------------------------
# LAMMPS input script generation
# ---------------------------------------------------------------------------

def _generate_lammps_input(input_path: Path, model_path: str,
                           element_types: list, *, ensemble: str = "npt",
                           temp: float = 300.0, pres: float = 1.0,
                           timestep: float = 0.001,
                           runtime_steps: int = 1_000_000,
                           dump_interval: int = 10000,
                           thermo_interval: int = 100) -> None:
    """Write a LAMMPS input script for DP-based MD.

    Parameters
    ----------
    input_path : Path
        Output file path (typically ``in.lammps``).
    model_path : str
        Path to the DeepMD model file, relative to the job directory.
    element_types : list[str]
        Sorted element symbols for the ``pair_coeff`` line.
    ensemble : str
        ``"npt"`` or ``"nve"``.
    temp : float
        Target temperature in K.
    pres : float
        Target pressure in bar (NPT only). LAMMPS units metal uses bar.
    timestep : float
        Timestep in ps (metal units).
    runtime_steps : int
        Number of MD steps.
    dump_interval : int
        Write trajectory every N steps.
    thermo_interval : int
        Print thermo every N steps.
    """
    elem_str = " ".join(element_types)

    if ensemble == "npt":
        fix_line = (f"fix             1 all npt temp {temp} {temp} 0.1 "
                    f"aniso {pres} {pres} 0.5")
    elif ensemble == "nve":
        fix_line = "fix             1 all nve"
    else:
        raise ValueError(f"Unsupported ensemble: {ensemble}. Use 'npt' or 'nve'.")

    content = f"""# LAMMPS input script for DeepMD potential
# Generated by lammps skill

units           metal
boundary        p p p
atom_style      atomic

neighbor        1.0 bin

read_data       conf.lmp

pair_style      deepmd {model_path}
pair_coeff      * * {elem_str}

velocity        all create {temp} 23456789
timestep        {timestep}
thermo          {thermo_interval}
thermo_style    custom step pe ke etotal temp press vol

{fix_line}
dump            1 all custom {dump_interval} traj.dump id type xu yu zu
dump_modify     1 sort id

run             {runtime_steps}

undump          1
unfix           1
"""
    with open(input_path, "w") as f:
        f.write(content)


# ---------------------------------------------------------------------------
# cmd_generate_input
# ---------------------------------------------------------------------------

def cmd_generate_input(args) -> dict:
    """Generate a LAMMPS job directory with ``in.lammps`` and ``conf.lmp``."""
    config = _load_config(args.config)
    work_dir = Path(config["work_dir"])
    work_dir.mkdir(parents=True, exist_ok=True)

    # ── Resolve model ──────────────────────────────────────────────────────
    local_model: Optional[Path] = None
    if args.model_path:
        local_model = Path(args.model_path).resolve()
        if not local_model.exists():
            raise FileNotFoundError(f"Model not found: {local_model}")
    else:
        env_model = _default_model_path()
        if env_model is not None:
            if not env_model.exists():
                raise FileNotFoundError(
                    f"DEEPMD_MODEL_PATH points to a missing file: {env_model}"
                )
            local_model = env_model.resolve()
        else:
            raise ValueError(
                "No model specified. Provide --model_path or set DEEPMD_MODEL_PATH."
            )

    # ── Read structures ────────────────────────────────────────────────────
    ensemble = args.ensemble.lower()
    all_frames = list(read(str(args.structures), index=":"))

    # Determine which frames to process
    if args.frame is None:
        frame_indices = [0]
    elif args.frame == -1:
        frame_indices = list(range(len(all_frames)))
    else:
        frame_indices = [args.frame]

    # ── Resolve head (same convention as ase-deepmd) ───────────────────────
    head = args.head
    if head and head.lower() == "none":
        head = None

    results = []
    for idx in frame_indices:
        atoms = all_frames[idx]

        # Build per-frame output directory
        job_dir = work_dir / f"lammps_{ensemble}_{_job_id()}"
        job_dir.mkdir(parents=True, exist_ok=True)

        # Copy / freeze model into job directory
        model_filename = _FROZEN_MODEL_FILENAME
        model_dest = job_dir / model_filename
        if head:
            _freeze_model(local_model, head, model_dest)
        else:
            shutil.copy2(str(local_model), str(model_dest))

        # Write LAMMPS data file
        data_path = job_dir / "conf.lmp"
        gen = _generate_lammps_data(atoms, data_path)

        # Generate input script
        input_path = job_dir / "in.lammps"
        _generate_lammps_input(
            input_path, model_filename, gen["element_types"],
            ensemble=ensemble, temp=args.temperature, pres=args.pressure,
            timestep=args.timestep, runtime_steps=args.runtime_steps,
            dump_interval=args.dump_interval, thermo_interval=args.thermo_interval,
        )

        # Save job metadata for later collection
        meta = {
            "ensemble": ensemble,
            "temperature_K": args.temperature,
            "pressure_bar": args.pressure if ensemble == "npt" else None,
            "runtime_steps": args.runtime_steps,
            "timestep_ps": args.timestep,
            "element_types": gen["element_types"],
            "type_map": gen["type_map"],
            "frame_index": idx,
            "source_file": str(args.structures),
        }
        with open(job_dir / "job_config.json", "w") as fp:
            json.dump(meta, fp, indent=2)

        results.append({
            "job_dir": str(job_dir),
            "input_file": str(input_path),
            "data_file": str(data_path),
            "model_file": str(model_dest),
            "frame_index": idx,
            "element_types": gen["element_types"],
        })

    return {
        "status": "success",
        "ensemble": ensemble,
        "temperature_K": args.temperature,
        "pressure_bar": args.pressure if ensemble == "npt" else None,
        "runtime_steps": args.runtime_steps,
        "num_jobs": len(results),
        "jobs": results,
    }


# ---------------------------------------------------------------------------
# cmd_collect_results
# ---------------------------------------------------------------------------

def _parse_lammps_log(log_path: Path) -> dict:
    """Parse a LAMMPS log file and extract thermo data."""
    with open(log_path) as f:
        lines = f.readlines()

    header = None
    data: List[dict] = []

    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue

        # Header line: starts with "Step" (first keyword of thermo_style)
        if header is None and stripped.startswith("Step"):
            header = stripped.split()
            continue

        if header is not None:
            # End of thermo block
            if stripped.startswith("Loop"):
                break
            parts = stripped.split()
            if len(parts) == len(header):
                try:
                    values = [float(x) for x in parts]
                    data.append(dict(zip(header, values)))
                except ValueError:
                    continue

    if not data:
        return {"steps": 0, "avg_temp": 0, "avg_press": 0,
                "avg_pe": 0, "avg_vol": 0, "thermo_data": []}

    temps = [d["Temp"] for d in data if "Temp" in d]
    press = [d["Press"] for d in data if "Press" in d]
    pe = [d["PotEng"] for d in data if "PotEng" in d]
    vol = [d["Volume"] for d in data if "Volume" in d]

    return {
        "steps": int(data[-1].get("Step", 0)),
        "avg_temp": sum(temps) / len(temps) if temps else 0,
        "avg_press": sum(press) / len(press) if press else 0,
        "avg_pe": sum(pe) / len(pe) if pe else 0,
        "avg_vol": sum(vol) / len(vol) if vol else 0,
        "thermo_data": data,
    }


def cmd_collect_results(args) -> dict:
    """Collect results from completed LAMMPS job directories."""
    calc_dirs = [Path(d) for d in args.calc_dirs]
    job_summaries: List[dict] = []

    for calc_dir in calc_dirs:
        log_path = calc_dir / "log.lammps"
        if not log_path.exists():
            job_summaries.append({
                "calc_dir": str(calc_dir),
                "status": "incomplete",
                "message": "log.lammps not found",
            })
            continue

        # Read job config
        config_path = calc_dir / "job_config.json"
        job_config = {}
        if config_path.exists():
            with open(config_path) as fp:
                job_config = json.load(fp)

        # Parse log
        thermo = _parse_lammps_log(log_path)
        expected_steps = job_config.get("runtime_steps", 0)
        actual_steps = thermo["steps"]

        if expected_steps > 0 and actual_steps < expected_steps * 0.99:
            status = "incomplete"
            message = (f"Simulation incomplete: {actual_steps}/{expected_steps} steps")
        else:
            status = "success"
            message = f"Completed {actual_steps} steps"

        summary = {
            "calc_dir": str(calc_dir),
            "status": status,
            "message": message,
            "ensemble": job_config.get("ensemble", "unknown"),
            "element_types": job_config.get("element_types", []),
            "steps_completed": actual_steps,
            "avg_temperature_K": round(thermo["avg_temp"], 2),
            "avg_pressure_bar": round(thermo["avg_press"], 6),
            "avg_potential_energy_eV": round(thermo["avg_pe"], 6),
            "avg_volume_A3": round(thermo["avg_vol"], 4),
        }

        # Check for trajectory dump
        traj_path = calc_dir / "traj.dump"
        if traj_path.exists():
            summary["trajectory_file"] = str(traj_path)

        job_summaries.append(summary)

    successful = [j for j in job_summaries if j["status"] == "success"]
    failed = [j for j in job_summaries if j["status"] != "success"]

    return {
        "status": "success",
        "total_jobs": len(job_summaries),
        "successful": len(successful),
        "failed": len(failed),
        "jobs": job_summaries,
    }


# ---------------------------------------------------------------------------
# cmd_show_model_path
# ---------------------------------------------------------------------------

def cmd_show_model_path(args) -> dict:
    """Return the resolved default model path from DEEPMD_MODEL_PATH."""
    model_path = _default_model_path()
    if model_path is None:
        return {
            "status": "not_set",
            "model_path": None,
            "message": "DEEPMD_MODEL_PATH is not set in the environment or .env file.",
        }
    return {
        "status": "ok",
        "model_path": str(model_path),
        "exists": model_path.exists(),
    }


# ---------------------------------------------------------------------------
# argparse
# ---------------------------------------------------------------------------

def _add_common_args(p: argparse.ArgumentParser) -> None:
    p.add_argument(
        "--config", type=Path, default=_DEFAULT_CONFIG,
        help=f"Path to config.yaml (default: {_DEFAULT_CONFIG}).",
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate LAMMPS input files for DeepMD MD simulations.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # ── generate_input ─────────────────────────────────────────────────────
    p = sub.add_parser("generate_input",
                       help="Generate in.lammps + conf.lmp for MD simulation.")
    _add_common_args(p)
    p.add_argument("--structures", required=True,
                   help="Path to structure file (extxyz, POSCAR, CIF, …).")
    p.add_argument("--model_path", type=str, default=None,
                   help="Path to DeePMD model file. Falls back to DEEPMD_MODEL_PATH env var.")
    p.add_argument("--head", type=str, default="Omat24",
                   help="Multi-task head to freeze (default: Omat24). "
                        "Pass 'none' to skip freezing and use the model as-is.")
    p.add_argument("--frame", type=int, default=None,
                   help="Frame index for multi-frame files. -1 = all frames (default: first frame).")
    p.add_argument("--ensemble", type=str, default="npt", choices=["npt", "nve"],
                   help="Ensemble: npt or nve (default: npt).")
    p.add_argument("--temperature", type=float, default=300.0,
                   help="Target temperature in K (default: 300).")
    p.add_argument("--pressure", type=float, default=1.0,
                   help="Target pressure in bar, NPT only (default: 1.0). LAMMPS units metal uses bar.")
    p.add_argument("--timestep", type=float, default=0.001,
                   help="Timestep in ps (default: 0.001).")
    p.add_argument("--runtime_steps", type=int, default=1_000_000,
                   help="Number of MD steps (default: 1000000).")
    p.add_argument("--dump_interval", type=int, default=10000,
                   help="Trajectory write frequency in steps (default: 10000).")
    p.add_argument("--thermo_interval", type=int, default=100,
                   help="Thermo output frequency in steps (default: 100).")
    p.set_defaults(func=cmd_generate_input)

    # ── collect_results ────────────────────────────────────────────────────
    p = sub.add_parser("collect_results",
                       help="Collect results from completed LAMMPS jobs.")
    p.add_argument("--calc_dirs", nargs="+", required=True,
                   help="Paths to LAMMPS job directories.")
    p.set_defaults(func=cmd_collect_results)

    # ── show_model_path ────────────────────────────────────────────────────
    p = sub.add_parser("show_model_path",
                       help="Show the default DeePMD model path.")
    p.set_defaults(func=cmd_show_model_path)

    args = parser.parse_args()
    _load_env(_DEFAULT_CONFIG)

    try:
        result = args.func(args)
        print(json.dumps(result, indent=2, default=str))
        sys.exit(0)
    except Exception as exc:
        print(
            json.dumps({"status": "error", "message": str(exc),
                        "traceback": traceback.format_exc()}),
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
