Transfer2Agent = "transfer_to_agent"
FRONTEND_STATE_KEY = "frontend_state"
TMP_FRONTEND_STATE_KEY = "tmp_frontend_state"
LOADING_STATE_KEY = "loading_state"
LOADING_START = "loading_start"
LOADING_END = "loading_end"
LOADING_DESC = "loading_desc"
LOADING_TITLE = "loading_title"