
DPA2_CONFIG_TEMPLATE = {
    "_comment": "The template configuration file for training DPA model",
    "model": {
        "_comment": "The 'type map' lists all the elements that will be included in the model. It is the only field that needs to be modified.",
        "type_map": [
             "H",
            "He",
            "Li",
            "Be",
            "B",
            "C",
            "N",
            "O",
            "F",
            "Ne",
            "Na",
            "Mg",
            "Al",
            "Si",
            "P",
            "S",
            "Cl",
            "Ar",
            "K",
            "Ca",
            "Sc",
            "Ti",
            "V",
            "Cr",
            "Mn",
            "Fe",
            "Co",
            "Ni",
            "Cu",
            "Zn",
            "Ga",
            "Ge",
            "As",
            "Se",
            "Br",
            "Kr",
            "Rb",
            "Sr",
            "Y",
            "Zr",
            "Nb",
            "Mo",
            "Tc",
            "Ru",
            "Rh",
            "Pd",
            "Ag",
            "Cd",
            "In",
            "Sn",
            "Sb",
            "Te",
            "I",
            "Xe",
            "Cs",
            "Ba",
            "La",
            "Ce",
            "Pr",
            "Nd",
            "Pm",
            "Sm",
            "Eu",
            "Gd",
            "Tb",
            "Dy",
            "Ho",
            "Er",
            "Tm",
            "Yb",
            "Lu",
            "Hf",
            "Ta",
            "W",
            "Re",
            "Os",
            "Ir",
            "Pt",
            "Au",
            "Hg",
            "Tl",
            "Pb",
            "Bi",
            "Po",
            "At",
            "Rn",
            "Fr",
            "Ra",
            "Ac",
            "Th",
            "Pa",
            "U",
            "Np",
            "Pu",
            "Am",
            "Cm",
            "Bk",
            "Cf",
            "Es",
            "Fm",
            "Md",
            "No",
            "Lr",
            "Rf",
            "Db",
            "Sg",
            "Bh",
            "Hs",
            "Mt",
            "Ds",
            "Rg",
            "Cn",
            "Nh",
            "Fl",
            "Mc",
            "Lv",
            "Ts",
            "Og"
        ],
        "descriptor": {
            "type": "dpa2",
            "repinit": {
                "tebd_dim": 8,
                "rcut": 6.0,
                "rcut_smth": 0.5,
                "nsel": 120,
                "neuron": [
                    25,
                    50,
                    100
                ],
                "axis_neuron": 12,
                "activation_function": "tanh",
                "three_body_sel": 40,
                "three_body_rcut": 4.0,
                "three_body_rcut_smth": 3.5,
                "use_three_body": True
            },
            "repformer": {
                "rcut": 4.0,
                "rcut_smth": 3.5,
                "nsel": 40,
                "nlayers": 6,
                "g1_dim": 128,
                "g2_dim": 32,
                "attn2_hidden": 32,
                "attn2_nhead": 4,
                "attn1_hidden": 128,
                "attn1_nhead": 4,
                "axis_neuron": 4,
                "update_h2": False,
                "update_g1_has_conv": True,
                "update_g1_has_grrg": True,
                "update_g1_has_drrd": True,
                "update_g1_has_attn": False,
                "update_g2_has_g1g1": False,
                "update_g2_has_attn": True,
                "update_style": "res_residual",
                "update_residual": 0.01,
                "update_residual_init": "norm",
                "attn2_has_gate": True,
                "use_sqrt_nnei": True,
                "g1_out_conv": True,
                "g1_out_mlp": True
            },
            "add_tebd_to_repinit_out": False
        },
        "fitting_net": {
            "neuron": [
                240,
                240,
                240
            ],
            "resnet_dt": True,
            "seed": 2509405570,
            "_comment": " that's all"
        },
    },
    "learning_rate": {
        "_comment": "The 'decay_steps' need to be dynamically updated based on the number of batches per epoch.",
        "type": "exp",
        "decay_steps": 10,
        "start_lr": 0.001,
        "stop_lr": 3.51e-08,
    },
    "loss": {
        "type": "ener",
        "start_pref_e": 0.02,
        "limit_pref_e": 1,
        "start_pref_f": 1000,
        "limit_pref_f": 1,
        "start_pref_v": 0,
        "limit_pref_v": 0,
        "_comment": " that's all"
    },
    "training": {
        "training_data": {
            "systems": [
            ],
            "batch_size": "auto",
            "_comment": "There is no need to modify here, training tool would handle it automatically.",
            "auto_prob": "prob_sys_size"
        },
        "_comment": "You do need to update the 'numb_steps' based on your training data size. Usually, it should correspond to 50-100 epochs.",
        "numb_steps": 100,
        "warmup_steps": 0,
        "gradient_max_norm": 5.0,
        "seed": 2912457061,
        "disp_file": "lcurve.out",
        "disp_freq": 100,
        "save_freq": 2000,
    }
}
